name: Push Shorebird Patch (iOS)

on:
  workflow_dispatch:

jobs:
  patch_ios:
    name: Push Shorebird Patch to iOS Devices
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Setup Shorebird
        uses: shorebirdtech/setup-shorebird@v1
        with:
          cache: true

      - name: Install Dependencies
        run: |
          cd frontend
          flutter pub get

      - name: Push Shorebird Patch
        env:
          SHOREBIRD_TOKEN: ${{ secrets.SHOREBIRD_TOKEN }}
        run: |
          cd frontend
          shorebird patch ios --no-codesign --release-version=latest --allow-asset-diffs
